import { components } from './licenceApiImport'

export type AdditionalCondition = components['schemas']['AdditionalCondition']
export type AppointmentAddressRequest = components['schemas']['AppointmentAddressRequest']
export type AppointmentPersonRequest = components['schemas']['AppointmentPersonRequest']
export type AppointmentTimeRequest = components['schemas']['AppointmentTimeRequest']
export type BespokeConditionsRequest = components['schemas']['BespokeConditionRequest']
export type AdditionalConditionsRequest = components['schemas']['AdditionalConditionsRequest']
export type UpdateAdditionalConditionDataRequest = components['schemas']['UpdateAdditionalConditionDataRequest']
export type AdditionalConditionData = components['schemas']['AdditionalConditionData']
export type ContactNumberRequest = components['schemas']['ContactNumberRequest']
export type CreateLicenceRequest = components['schemas']['CreateLicenceRequest']
export type LicenceSummary = components['schemas']['LicenceSummary']
export type Licence = components['schemas']['Licence']
export type StatusUpdateRequest = components['schemas']['StatusUpdateRequest']
