import { components } from './licenceApiImport'

export type AdditionalCondition = components['schemas']['AdditionalCondition']
export type AppointmentAddressRequest = components['schemas']['AppointmentAddressRequest']
export type AppointmentPersonRequest = components['schemas']['AppointmentPersonRequest']
export type AppointmentTimeRequest = components['schemas']['AppointmentTimeRequest']
export type AuditEvent = components['schemas']['AuditEvent']
export type AuditRequest = components['schemas']['AuditRequest']
export type BespokeCondition = components['schemas']['BespokeCondition']
export type BespokeConditionsRequest = components['schemas']['BespokeConditionRequest']
export type AdditionalConditionsRequest = components['schemas']['AdditionalConditionsRequest']
export type UpdateStandardConditionDataRequest = components['schemas']['UpdateStandardConditionDataRequest']
export type UpdateAdditionalConditionDataRequest = components['schemas']['UpdateAdditionalConditionDataRequest']
export type AdditionalConditionData = components['schemas']['AdditionalConditionData']
export type ContactNumberRequest = components['schemas']['ContactNumberRequest']
export type CreateLicenceRequest = components['schemas']['CreateLicenceRequest']
export type CreateLicenceResponse = components['schemas']['CreateLicenceResponse']
export type CreateVariationResponse = components['schemas']['CreateVariationResponse']
export type EditLicenceResponse = components['schemas']['EditLicenceResponse']
export type LicenceSummary = components['schemas']['LicenceSummary']
export type Licence =
  | components['schemas']['HdcVariationLicence']
  | components['schemas']['VariationLicence']
  | components['schemas']['HardStopLicence']
  | components['schemas']['CrdLicence']
  | components['schemas']['HdcLicence']
  | components['schemas']['PrrdLicenceResponse']
  | components['schemas']['TimeServedLicence']
export type VariationLicence = components['schemas']['VariationLicence']
export type HdcLicence = components['schemas']['HdcLicence']
export type HdcVariationLicence = components['schemas']['HdcVariationLicence']
export type LicenceEvent = components['schemas']['LicenceEvent']
export type StatusUpdateRequest = components['schemas']['StatusUpdateRequest']
export type UpdateComRequest = components['schemas']['UpdateComRequest']
export type UpdatePrisonUserRequest = components['schemas']['UpdatePrisonUserRequest']
export type AddAdditionalConditionRequest = components['schemas']['AddAdditionalConditionRequest']
export type UpdateSpoDiscussionRequest = components['schemas']['UpdateSpoDiscussionRequest']
export type UpdateVloDiscussionRequest = components['schemas']['UpdateVloDiscussionRequest']
export type UpdateReasonForVariationRequest = components['schemas']['UpdateReasonForVariationRequest']
export type UpdatePrisonInformationRequest = components['schemas']['UpdatePrisonInformationRequest']
export type ReferVariationRequest = components['schemas']['ReferVariationRequest']
export type NotifyRequest = components['schemas']['NotifyRequest']
export type OmuContact = components['schemas']['OmuContact']
export type LicencePolicyResponse = components['schemas']['LicencePolicy']
export type StandardConditions = components['schemas']['StandardConditions']
export type StandardCondition = components['schemas']['StandardCondition']
export type AdditionalConditionsResponse = components['schemas']['AdditionalConditions']
export type AdditionalConditionApResponse = components['schemas']['AdditionalConditionAp']
export type AdditionalConditionPssResponse = components['schemas']['AdditionalConditionPss']
export type Input = components['schemas']['Input']
export type LicenceConditionChange = components['schemas']['LicenceConditionChanges']
export type OverrideLicenceDatesRequest = components['schemas']['OverrideLicenceDatesRequest']
export type OverrideLicenceTypeRequest = components['schemas']['OverrideLicenceTypeRequest']
export type OverrideLicencePrisonerDetailsRequest = components['schemas']['OverrideLicencePrisonerDetailsRequest']
export type UpdateOffenderDetailsRequest = components['schemas']['UpdateOffenderDetailsRequest']
export type ProbationSearchRequest = components['schemas']['ProbationUserSearchRequest']
export type ComSearchResponse = components['schemas']['ComSearchResponse']
export type FoundComCase = components['schemas']['FoundComCase']
export type ComReviewCount = components['schemas']['ComReviewCount']
export type CvlPrisoner = components['schemas']['Prisoner']
export type CvlFields = components['schemas']['CvlFields']
export type PrisonerWithCvlFields = components['schemas']['PrisonerWithCvlFields']
export type ApprovalCase = components['schemas']['ApprovalCase']
export type CaCaseloadSearch = components['schemas']['CaCaseloadSearch']
export type CaCase = components['schemas']['CaCase']
export type ComCreateCase = components['schemas']['ComCreateCase']
export type ComVaryCase = components['schemas']['ComVaryCase']
export type TeamCaseloadRequest = components['schemas']['TeamCaseloadRequest']
export type HdcLicenceData = components['schemas']['HdcLicenceData']
export type VaryApproverCaseloadSearchRequest = components['schemas']['VaryApproverCaseloadSearchRequest']
export type VaryApproverCaseloadSearchResponse = components['schemas']['VaryApproverCaseloadSearchResponse']
export type VaryApproverCase = components['schemas']['VaryApproverCase']
export type ElectronicMonitoringProvider = components['schemas']['ElectronicMonitoringProvider']
export type PrisonUserSearchRequest = components['schemas']['PrisonUserSearchRequest']
export type PrisonCaseAdminSearchResult = components['schemas']['PrisonCaseAdminSearchResult']
export type LastMinuteHandoverCaseResponse = components['schemas']['LastMinuteHandoverCaseResponse']
export type UpcomingReleasesWithMonitoringConditionsResponse =
  components['schemas']['UpcomingReleasesWithMonitoringConditionsResponse']

export type ApproverSearchRequest = components['schemas']['ApproverSearchRequest']
export type ApproverSearchResponse = components['schemas']['ApproverSearchResponse']
export type UpdateElectronicMonitoringProgrammeRequest =
  components['schemas']['UpdateElectronicMonitoringProgrammeRequest']
export type AddressSearchResponse = components['schemas']['AddressSearchResponse']
export type AddAddressRequest = components['schemas']['AddAddressRequest']
export type AddressResponse = components['schemas']['AddressResponse']
export type LicencePermissionsRequest = components['schemas']['LicencePermissionsRequest']
export type LicencePermissionsResponse = components['schemas']['LicencePermissionsResponse']
export type TimeServedCase = components['schemas']['TimeServedCase']
export type TimeServedCaseload = components['schemas']['TimeServedCaseload']
export type EligibilityAssessment = components['schemas']['EligibilityAssessment']
export type ExternalTimeServedRecordRequest = components['schemas']['ExternalTimeServedRecordRequest']
export type ExternalTimeServedRecordResponse = components['schemas']['ExternalTimeServedRecordResponse']
export type TimeServedProbationConfirmContactRequest = components['schemas']['TimeServedProbationConfirmContactRequest']
