import { templateRenderer } from '../../utils/__testutils/templateTestUtils'

describe('View Partials - Vary Call To Actions', () => {
  describe('activeCta', () => {
    it('renders "Vary licence" button and heading when shouldShowVaryButton=true and showTitle=true', () => {
      // Given
      const callToActions = { shouldShowVaryButton: true }
      const licence = createLicence({ id: 123 })
      const showTitle = true

      // When
      const $ = renderActiveCta({ callToActions, licence, showTitle, csrfToken: 'token' })

      // Then
      expect($('h2.govuk-heading-m').text().trim()).toBe('Vary this licence')
      const varyLicenceLink = $('a[data-qa="vary-licence"]')
      expect(varyLicenceLink.text().trim()).toBe('Vary licence')
      expect(varyLicenceLink.attr('href')).toBe('/licence/vary/id/123/confirm-vary-action')
    })

    it('renders button without heading when showTitle=false', () => {
      // Given
      const callToActions = { shouldShowVaryButton: true }
      const licence = createLicence({ id: 123 })
      const showTitle = false

      // When
      const $ = renderActiveCta({ callToActions, licence, showTitle, csrfToken: 'token' })

      // Then
      expect($('h2.govuk-heading-m').length).toBe(0)
      expect($('a[data-qa="vary-licence"]').length).toBe(1)
    })

    it('renders nothing when shouldShowVaryButton=false', () => {
      // Given
      const callToActions = { shouldShowVaryButton: false }
      const licence = createLicence({ id: 123 })
      const showTitle = true

      // When
      const $ = renderActiveCta({ callToActions, licence, showTitle, csrfToken: 'token' })

      // Then
      expect($('h2.govuk-heading-m').length).toBe(0)
      expect($('a[data-qa="vary-licence"]').length).toBe(0)
    })
  })

  describe('submittedCta', () => {
    it('renders Edit and Discard buttons when shouldShowEditAndDiscardButton=true', () => {
      // Given
      const callToActions = { shouldShowEditAndDiscardButton: true }
      const licence = createLicence({ id: 456 })

      // When
      const $ = renderSubmittedCta({ callToActions, licence, csrfToken: 'token' })

      // Then
      expect($('a:contains("Edit variation")').attr('href')).toBe('/licence/vary/id/456/confirm-amend-variation')
      expect($('a:contains("Discard variation")').attr('href')).toBe('/licence/vary/id/456/confirm-discard-variation')
    })

    it('renders nothing when shouldShowEditAndDiscardButton=false', () => {
      // Given
      const callToActions = { shouldShowEditAndDiscardButton: false }
      const licence = createLicence({ id: 456 })

      // When
      const $ = renderSubmittedCta({ callToActions, licence, csrfToken: 'token' })

      // Then
      expect($('a:contains("Edit variation")').length).toBe(0)
      expect($('a:contains("Discard variation")').length).toBe(0)
    })
  })

  describe('timelineCta', () => {
    const actionCases = [
      ['PRINT_TO_ACTIVATE', 'Set licence to active', 'view-and-print'],
      ['VIEW_OR_VARY', 'View or vary licence', 'view-or-vary-licence'],
      ['VIEW', 'View licence', 'view-licence'],
      ['EDIT', 'Edit variation', 'edit-licence'],
    ]

    it.each(actionCases)('renders primary button for %s action', (action, text, dataQa) => {
      // Given
      const licence = createLicence()

      // When
      const $ = renderTimelineCta({ callToAction: action, licence, csrfToken: 'token' })

      // Then
      expect($(`a[data-qa="${dataQa}"], button[data-qa="${dataQa}"]`).text().trim()).toBe(text)
    })

    it('renders warning text and buttons for REVIEW with TIME_SERVED licence', () => {
      // Given
      const licence = createLicence({ id: 1, kind: 'TIME_SERVED' })

      // When
      const $ = renderTimelineCta({ callToAction: 'REVIEW', licence, csrfToken: 'token' })

      // Then
      expect($('.govuk-warning-text__text').text()).toContain(
        'Review needed - This person was released with time served on a standard licence generated by the prison.',
      )
      expect($('a:contains("Review licence")').attr('href')).toBe('/licence/vary/id/1/have-you-reviewed-this-licence')
      expect($('a:contains("Return to case list")').attr('href')).toBe('/licence/vary/caseload')
    })

    it('renders warning text and buttons for REVIEW with STANDARD licence', () => {
      // Given
      const licence = createLicence({ id: 1, kind: 'STANDARD' })

      // When
      const $ = renderTimelineCta({ callToAction: 'REVIEW', licence, csrfToken: 'token' })

      // Then
      expect($('.govuk-warning-text__text').text()).toContain(
        "Review needed – Standard licence generated by the prison as you did not get one approved in time for the prison's final release checks.",
      )
      expect($('a:contains("Review licence")').attr('href')).toBe('/licence/vary/id/1/have-you-reviewed-this-licence')
      expect($('a:contains("Return to case list")').attr('href')).toBe('/licence/vary/caseload')
    })
  })

  const renderActiveCta = templateRenderer(
    '{% from "partials/varyCallToActions.njk" import activeCta %}{{ activeCta(callToActions, licence, showTitle, csrfToken)}}',
  )
  const renderSubmittedCta = templateRenderer(
    '{% from "partials/varyCallToActions.njk" import submittedCta %}{{ submittedCta(callToActions, licence, csrfToken)}}',
  )
  const renderTimelineCta = templateRenderer(
    '{% from "partials/varyCallToActions.njk" import timelineCta %}{{ timelineCta(callToAction, licence, csrfToken)}}',
  )

  const createLicence = (overrides = {}) => ({
    id: 1,
    kind: 'STANDARD',
    ...overrides,
  })
})
