enum conditionChangeType {
  DELETED = 'DELETED',
  NEW_OPTIONS = 'NEW_OPTIONS',
  REPLACED = 'REPLACED',
  TEXT_CHANGE = 'TEXT_CHANGE',
  REMOVED_NO_REPLACEMENTS = 'REMOVED_NO_REPLACEMENTS',
}

export default conditionChangeType
