enum LicenceStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  INACTIVE = 'INACTIVE',
  RECALLED = 'RECALLED',
  APPROVED = 'APPROVED',
  NOT_STARTED = 'NOT_STARTED',
  VARIATION_IN_PROGRESS = 'VARIATION_IN_PROGRESS',
  VARIATION_SUBMITTED = 'VARIATION_SUBMITTED',
}

export default LicenceStatus
