enum LicenceCreationType {
  LICENCE_CHANGES_NOT_APPROVED_IN_TIME = 'LICENCE_CHANGES_NOT_APPROVED_IN_TIME',
  PRISON_WILL_CREATE_THIS_LICENCE = 'PRISON_WILL_CREATE_THIS_LICENCE',
  LICENCE_CREATED_BY_PRISON = 'LICENCE_CREATED_BY_PRISON',
  LICENCE_NOT_STARTED = 'LICENCE_NOT_STARTED',
  LICENCE_IN_PROGRESS = 'LICENCE_IN_PROGRESS',
}

export default LicenceCreationType
