enum LicenceEventType {
  CREATED = 'CREATED',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  ACTIVATED = 'ACTIVATED',
  SUPERSEDED = 'SUPERSEDED',
  VARIATION_CREATED = 'VARIATION_CREATED',
  VARIATION_SUBMITTED_REASON = 'VARIATION_SUBMITTED_REASON',
  VARIATION_SUBMITTED = 'VARIATION_SUBMITTED',
  VARIATION_REFERRED = 'VARIATION_REFERRED',
  VARIATION_APPROVED = 'VARIATION_APPROVED',
  REVIEWED_WITHOUT_VARIATION = 'REVIEWED_WITHOUT_VARIATION',
  REVIEWED_WITH_VARIATION = 'REVIEWED_WITH_VARIATION',
}

export default LicenceEventType
