enum LicenceStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  INACTIVE = 'INACTIVE',
  RECALLED = 'RECALLED',
  APPROVED = 'APPROVED',
  NOT_STARTED = 'NOT_STARTED',
  VARIATION_IN_PROGRESS = 'VARIATION_IN_PROGRESS',
  VARIATION_SUBMITTED = 'VARIATION_SUBMITTED',
  VARIATION_REJECTED = 'VARIATION_REJECTED',
  VARIATION_APPROVED = 'VARIATION_APPROVED',
  NOT_IN_PILOT = 'NOT_IN_PILOT',
  OOS_BOTUS = 'OOS_BOTUS',
  OOS_RECALL = 'OOS_RECALL',
  // ON_PSS status is not saved within licence and only added here in order to show it as a label in the UI
  ON_PSS = 'ON_PSS',
}

export default LicenceStatus
