enum TimelineEventType {
  CREATION = 'CREATION',
  VARIATION = 'VARIATION',
  VARIATION_IN_PROGRESS = 'VARIATION_IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  REJECTED = 'REJECTED',
  REVIEWED_WITHOUT_VARIATION = 'REVIEWED_WITHOUT_VARIATION',
}

export default TimelineEventType
