/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/offender/crn/{crn}/responsible-com': {
    /** Updates in-flight licences associated with an offender with the community offender manager who is responsible for that offender. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
    put: operations['updateResponsibleCom']
  }
  '/licence/id/{licenceId}/submit': {
    /** Update the status of a licence to SUBMITTED, and record the details of the COM who submitted. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
    put: operations['submitLicence']
  }
  '/licence/id/{licenceId}/status': {
    /** Update the status of a licence. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
    put: operations['updateLicenceStatus']
  }
  '/licence/id/{licenceId}/contact-number': {
    /** Update the contact number for the officer related to this licence. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
    put: operations['updateContactNumber']
  }
  '/licence/id/{licenceId}/bespoke-conditions': {
    /** Add or replace the bespoke conditions on a licence with the content of this request. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
    put: operations['updateBespokeConditions']
  }
  '/licence/id/{licenceId}/appointmentTime': {
    /** Update the date and time for the initial appointment. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
    put: operations['updateAppointmentTime']
  }
  '/licence/id/{licenceId}/appointmentPerson': {
    /** Update the person the person on probation will meet at the initial appointment Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
    put: operations['updateAppointmentPerson']
  }
  '/licence/id/{licenceId}/appointment-address': {
    /** Update the address where the initial appointment will take place. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
    put: operations['updateAppointmentAddress']
  }
  '/licence/id/{licenceId}/additional-conditions': {
    /** Update the set of additional conditions on the licence. This does not include accompanying data per condition. Existing conditions which appear on the licence but which are not supplied to this endpoint will be deleted. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
    put: operations['updateAdditionalConditions']
  }
  '/licence/id/{licenceId}/additional-conditions/condition/{additionalConditionId}': {
    /** Update the user entered data to accompany an additional condition template. Existing data for a condition which does not appear in this request will be deleted. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
    put: operations['updateAdditionalConditionData']
  }
  '/exclusion-zone/id/{licenceId}/condition/id/{conditionId}/remove-upload': {
    /** Removes a previously uploaded exclusion zone file. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
    put: operations['removeExclusionZoneFile']
  }
  '/audit/save': {
    /** Records an auditable event related to an action taken by a user or an automated in-service process. Requires ROLE_CVL_ADMIN. */
    put: operations['recordAuditEvent']
  }
  '/licence/create': {
    /** Creates a licence with the default status IN_PROGRESS and populates with the details provided. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
    post: operations['createLicence']
  }
  '/licence/activate-licences': {
    /** Set licence statuses to ACTIVE. Accepts a list of licence IDs. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
    post: operations['activateLicences']
  }
  '/exclusion-zone/id/{licenceId}/condition/id/{conditionId}/file-upload': {
    /** Uploads a PDF file containing an exclusion zone map and description. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
    post: operations['uploadExclusionZoneFile']
  }
  '/audit/retrieve': {
    /** Retrieves a list of auditable events matching the criteria provided. Requires ROLE_CVL_ADMIN. */
    post: operations['requestAuditEvents']
  }
  '/licence/match': {
    /** Get the licences matching the supplied lists of status, prison, staffId and nomsId. Requires ROLE_CVL_ADMIN. */
    get: operations['getLicencesMatchingCriteria']
  }
  '/licence/id/{licenceId}': {
    /** Returns a single licence detail by its unique identifier. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
    get: operations['getLicenceById']
  }
  '/exclusion-zone/id/{licenceId}/condition/id/{conditionId}/full-size-image': {
    /** Get the exclusion zone map image. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
    get: operations['getExclusionZoneImage']
  }
}

export interface components {
  schemas: {
    /** Request object for updating the COM responsible for an offender */
    UpdateResponsibleComRequest: {
      /** The unique identifier of the responsible COM, retrieved from Delius */
      staffIdentifier: number
      /** The Delius username for the responsible COM */
      staffUsername: string
      /** The email address of the responsible COM */
      staffEmail: string
    }
    ErrorResponse: {
      status: number
      errorCode?: number
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
    /** Request object for submitting a licence */
    SubmitLicenceRequest: {
      /** The username of the person who is updating this status */
      username: string
      /** The DELIUS staff identifier of the person who is submitting status */
      staffIdentifier: number
      /** The first name of the person who is submitting the licence */
      firstName: string
      /** The last name of the person who is submitting the licence */
      surname: string
      /** The email address of the person who is submitting the licence */
      email: string
    }
    /** Request object for updating the status of a licence */
    StatusUpdateRequest: {
      /** The new status for this licence */
      status: 'IN_PROGRESS' | 'SUBMITTED' | 'APPROVED' | 'ACTIVE' | 'REJECTED' | 'INACTIVE' | 'RECALLED'
      /** The username of the person who is updating this status */
      username: string
      /** The full name of the person who is updating this status */
      fullName?: string
    }
    /** Request object for updating the contact number of the officer on a licence */
    ContactNumberRequest: {
      /** The UK telephone number to contact the person the offender should meet for their initial meeting */
      telephone: string
    }
    /** A list of bespoke conditions to add to a licence */
    BespokeConditionRequest: {
      /** A list of bespoke conditions to add to a licence */
      conditions: string[]
    }
    /** Request object for updating the date and time of the initial appointment */
    AppointmentTimeRequest: {
      /** The date and time of the initial appointment */
      appointmentTime: string
    }
    /** Request object for updating the person the person on probation will meet at the initial appointment */
    AppointmentPersonRequest: {
      /** The name of the person the person on probation will meet at the initial appointment */
      appointmentPerson: string
    }
    /** Request object for updating the address of the initial appointment */
    AppointmentAddressRequest: {
      /** The address of initial appointment */
      appointmentAddress: string
    }
    /** Describes an additional condition */
    AdditionalCondition: {
      /** The internal ID for this additional condition for this licence */
      id?: number
      /** Coded value for the additional condition */
      code?: string
      /** The category of the additional condition */
      category?: string
      /** Sequence of this additional condition within the additional conditions */
      sequence?: number
      /** The textual value for this additional condition */
      text?: string
      /** The list of data items entered for this additional condition */
      data: components['schemas']['AdditionalConditionData'][]
      /** The list of file upload summary for this additional condition */
      uploadSummary: components['schemas']['AdditionalConditionUploadSummary'][]
    }
    /** Describes the data entered for an additional condition */
    AdditionalConditionData: {
      /** The internal ID of this data item, for this condition on this licence */
      id: number
      /** The field name of this data item for this condition on this licence */
      field?: string
      /** The value of this data item */
      value?: string
      /** The sequence of this data item, for this condition on this licence */
      sequence: number
    }
    /** Describes the files uploaded for an additional condition */
    AdditionalConditionUploadSummary: {
      /** The internal ID of this upload for this condition on this licence */
      id: number
      /** The original file name uploaded for this condition on this licence */
      filename?: string
      /** The file type uploaded for this condition on this licence */
      fileType?: string
      /** The original file size in bytes */
      fileSize: number
      /** The date and time this file was uploaded */
      uploadedTime: string
      /** The description provided in this document */
      description?: string
      /** The thumbnail for the  exclusion zone map as a base64-encoded JPEG image */
      thumbnailImage?: string
      /** The id which references the original file data and full size image */
      uploadDetailId: number
    }
    /** Request object for updating the list of additional conditions on a licence */
    AdditionalConditionsRequest: {
      /** The list of additional conditions */
      additionalConditions: components['schemas']['AdditionalCondition'][]
      /** The type of additional condition, either licence or post sentence supervision */
      conditionType: 'AP' | 'PSS'
    }
    /** Request object for updating the list of additional conditions on a licence */
    UpdateAdditionalConditionDataRequest: {
      /** The list of data inputs associated with this additional condition */
      data: components['schemas']['AdditionalConditionData'][]
    }
    /** Describes an audit event request */
    AuditEvent: {
      /** The internal ID of the audit event */
      id?: number
      /** The internal ID of the licence that this event related to, or null if unrelated to a licence */
      licenceId?: number
      /** The date and time of the event */
      eventTime: string
      /** Username who initiated the event, if a user event, or SYSTEM if an automated event */
      username?: string
      /** The full name of the person who performed this auditable event, or SYSTEM if an automated event. */
      fullName?: string
      /** The event type. One of SYSTEM_EVENT or USER_EVENT */
      eventType: 'USER_EVENT' | 'SYSTEM_EVENT'
      /** A summary of the action taken */
      summary: string
      /** A detailed description of the action taken */
      detail?: string
    }
    /** Request object for creating a new licence */
    CreateLicenceRequest: {
      /** The username of the person who is creating the licence */
      username: string
      /** Type of licence requested - one of AP, PSS or AP_PSS */
      typeCode: 'AP' | 'AP_PSS' | 'PSS'
      /** The version of licence conditions currently active as a string value */
      version: string
      /** The prison nomis identifier for this offender */
      nomsId: string
      /** The prison booking number for the current sentence for this offender */
      bookingNo: string
      /** The prison booking id for the current sentence for this offender */
      bookingId: number
      /** The case reference number (CRN) of this person, from either prison or probation service */
      crn: string
      /** The police national computer number (PNC) of this person, from either prison or probation service */
      pnc?: string
      /** The criminal records office (CRO) identifier police of this person, from either prison or probation service */
      cro?: string
      /** The prison location code where this person is currently resident - leave null if not in prison */
      prisonCode: string
      /** The prison description - leave null if not in prison */
      prisonDescription: string
      /** The prison telephone number - leave null if not in prison */
      prisonTelephone?: string
      /** The offender forename */
      forename: string
      /** The offender middle names */
      middleNames?: string
      /** The offender surname */
      surname: string
      /** The offender's date of birth, from either prison or probation services */
      dateOfBirth: string
      /** The conditional release date, from prison services */
      conditionalReleaseDate?: string
      /** The actual release date, from prison services */
      actualReleaseDate?: string
      /** The sentence start date, from prison services */
      sentenceStartDate?: string
      /** The sentence end date, from prison services */
      sentenceEndDate?: string
      /** The licence start date, from prison services */
      licenceStartDate?: string
      /** The licence end date, from prison services */
      licenceExpiryDate?: string
      /** The date when the post sentence supervision period starts, from prison services */
      topupSupervisionStartDate?: string
      /** The date when the post sentence supervision period ends, from prison services */
      topupSupervisionExpiryDate?: string
      /** The telephone contact number for the offender manager, from probation services */
      comTelephone?: string
      /** The probation area code where the offender manager is based, from probation services */
      probationAreaCode: string
      /** The local delivery unit code where the offender manager works, from probation services */
      probationLduCode: string
      /** The list of standard licence conditions from service configuration */
      standardLicenceConditions: components['schemas']['StandardCondition'][]
      /** The list of standard post sentence supervision conditions from service configuration */
      standardPssConditions: components['schemas']['StandardCondition'][]
    }
    /** Describes a standard condition on this licence */
    StandardCondition: {
      /** The internal ID for this standard condition on this licence */
      id?: number
      /** The unique code for this standard condition */
      code?: string
      /** The sequence of this standard condition */
      sequence?: number
      /** The text of this standard condition */
      text?: string
    }
    /** Response object which summarises a licence */
    LicenceSummary: {
      /** Internal identifier for this licence generated within this service */
      licenceId: number
      /** Licence type code */
      licenceType: 'AP' | 'AP_PSS' | 'PSS'
      /** The status of this licence */
      licenceStatus: 'IN_PROGRESS' | 'SUBMITTED' | 'APPROVED' | 'ACTIVE' | 'REJECTED' | 'INACTIVE' | 'RECALLED'
      /** The prison nomis identifier for this offender */
      nomisId?: string
      /** The offender surname */
      surname?: string
      /** The offender forename */
      forename?: string
      /** The prison code where this offender resides or was released from */
      prisonCode?: string
      /** The prison where this offender resides or was released from */
      prisonDescription?: string
      /** The conditional release date on the licence */
      conditionalReleaseDate?: string
      /** The actual release date on the licence */
      actualReleaseDate?: string
      /** The case reference number (CRN) of this person, from either prison or probation service */
      crn?: string
      /** The offender's date of birth, from either prison or probation services */
      dateOfBirth?: string
      /** The username of the responsible probation officer */
      comUsername?: string
    }
    /** Describes an audit event request */
    AuditRequest: {
      /** The internal ID of the licence to request audit events for */
      licenceId?: number
      /** Username to request events for */
      username?: string
      /** The start date and time to query for events (default is 1 month ago) */
      startTime: string
      /** The end time to query for events (default is now) */
      endTime: string
    }
    /** Describes a bespoke condition on a licence */
    BespokeCondition: {
      /** The internal ID for this condition on this licence */
      id: number
      /** The sequence of this bespoke condition on this licence */
      sequence?: number
      /** The text of this bespoke condition */
      text?: string
    }
    /** Describes a licence document within this service */
    Licence: {
      /** Unique identifier for this licence within the service */
      id: number
      /** The licence type code */
      typeCode: 'AP' | 'AP_PSS' | 'PSS'
      /** The version number used for standard and additional conditions */
      version?: string
      /** The current status code for this licence */
      statusCode?: 'IN_PROGRESS' | 'SUBMITTED' | 'APPROVED' | 'ACTIVE' | 'REJECTED' | 'INACTIVE' | 'RECALLED'

      /** The prison identifier for the person on this licence */
      nomsId?: string
      /** The prison booking number for the person on this licence */
      bookingNo?: string
      /** The prison internal booking ID for the person on this licence */
      bookingId?: number
      /** The case reference number (CRN) for the person on this licence */
      crn?: string
      /** The police national computer number (PNC) for the person on this licence */
      pnc?: string
      /** The criminal records office number (CRO) for the person on this licence */
      cro?: string
      /** The agency code of the detaining prison */
      prisonCode?: string
      /** The agency description of the detaining prison */
      prisonDescription?: string
      /** The telephone number to contact the prison */
      prisonTelephone?: string
      /** The first name of the person on licence */
      forename?: string
      /** The middle names of the person on licence */
      middleNames?: string
      /** The family name of the person on licence */
      surname?: string
      /** The date of birth of the person on licence */
      dateOfBirth?: string
      /** The earliest conditional release date of the person on licence */
      conditionalReleaseDate?: string
      /** The actual release date (if set) */
      actualReleaseDate?: string
      /** The sentence start date */
      sentenceStartDate?: string
      /** The sentence end date */
      sentenceEndDate?: string
      /** The date that the licence will start */
      licenceStartDate?: string
      /** The date that the licence will expire */
      licenceExpiryDate?: string
      /** The date when the post sentence supervision period starts, from prison services */
      topupSupervisionStartDate?: string
      /** The date when the post sentence supervision period ends, from prison services */
      topupSupervisionExpiryDate?: string
      /** The first name of the supervising probation officer */
      comFirstName?: string
      /** The last name of the supervising probation officer */
      comLastName?: string
      /** The nDELIUS user name for the supervising probation officer */
      comUsername?: string
      /** The nDELIUS staff identifier for the supervising probation officer */
      comStaffId?: number
      /** The email address for the supervising probation officer */
      comEmail?: string
      /** The contact telephone number for the supervising probation officer */
      comTelephone?: string
      /** The code for the probation area where the supervising officer is located */
      probationAreaCode?: string
      /** The local delivery unit (LDU) code who supervises this licence */
      probationLduCode?: string
      /** Who the person will meet at their initial appointment */
      appointmentPerson?: string
      /** The date and time of the initial appointment */
      appointmentTime?: string
      /** The address of initial appointment */
      appointmentAddress?: string
      /** The UK telephone number to contact the person the offender should meet for their initial meeting */
      appointmentContact?: string
      /** The date and time that this prison approved this licence */
      approvedDate?: string
      /** The username who approved the licence on behalf of the prison governor */
      approvedByUsername?: string
      /** The full name of the person who approved the licence on behalf of the prison governor */
      approvedByName?: string
      /** The date and time that this licence was superseded by a new variant */
      supersededDate?: string
      /** The date and time that this licence was first created */
      dateCreated?: string
      /** The username which created this licence */
      createdByUsername?: string
      /** The date and time that this licence was last updated */
      dateLastUpdated?: string
      /** The username of the person who last updated this licence */
      updatedByUsername?: string
      /** The list of standard licence conditions on this licence */
      standardLicenceConditions?: components['schemas']['StandardCondition'][]
      /** The list of standard post sentence supervision conditions on this licence */
      standardPssConditions?: components['schemas']['StandardCondition'][]
      /** The list of additional licence conditions on this licence */
      additionalLicenceConditions: components['schemas']['AdditionalCondition'][]
      /** The list of additional post sentence supervision conditions on this licence */
      additionalPssConditions: components['schemas']['AdditionalCondition'][]
      /** The list of bespoke conditions on this licence */
      bespokeConditions: components['schemas']['BespokeCondition'][]
    }
  }
}

export interface operations {
  /** Updates in-flight licences associated with an offender with the community offender manager who is responsible for that offender. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
  updateResponsibleCom: {
    parameters: {
      path: {
        crn: string
      }
    }
    responses: {
      /** The responsible COM was updated */
      200: unknown
      /** Bad request, request body must be valid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateResponsibleComRequest']
      }
    }
  }
  /** Update the status of a licence to SUBMITTED, and record the details of the COM who submitted. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
  submitLicence: {
    parameters: {
      path: {
        licenceId: number
      }
    }
    responses: {
      /** Licence submitted for approval */
      200: unknown
      /** Bad request, request body must be valid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** The licence for this ID was not found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SubmitLicenceRequest']
      }
    }
  }
  /** Update the status of a licence. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
  updateLicenceStatus: {
    parameters: {
      path: {
        licenceId: number
      }
    }
    responses: {
      /** Licence status updated */
      200: unknown
      /** Bad request, request body must be valid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** The licence for this ID was not found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['StatusUpdateRequest']
      }
    }
  }
  /** Update the contact number for the officer related to this licence. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
  updateContactNumber: {
    parameters: {
      path: {
        licenceId: number
      }
    }
    responses: {
      /** Contact number updated */
      200: unknown
      /** Bad request, request body must be valid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** The licence for this ID was not found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ContactNumberRequest']
      }
    }
  }
  /** Add or replace the bespoke conditions on a licence with the content of this request. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
  updateBespokeConditions: {
    parameters: {
      path: {
        licenceId: number
      }
    }
    responses: {
      /** Bespoke conditions added or replaced */
      200: unknown
      /** Bad request, request body must be valid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** The licence for this ID was not found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BespokeConditionRequest']
      }
    }
  }
  /** Update the date and time for the initial appointment. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
  updateAppointmentTime: {
    parameters: {
      path: {
        licenceId: number
      }
    }
    responses: {
      /** Appointment date and time updated */
      200: unknown
      /** Bad request, request body must be valid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** The licence for this ID was not found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AppointmentTimeRequest']
      }
    }
  }
  /** Update the person the person on probation will meet at the initial appointment Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
  updateAppointmentPerson: {
    parameters: {
      path: {
        licenceId: number
      }
    }
    responses: {
      /** Appointment person updated */
      200: unknown
      /** Bad request, request body must be valid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** The licence for this ID was not found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AppointmentPersonRequest']
      }
    }
  }
  /** Update the address where the initial appointment will take place. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
  updateAppointmentAddress: {
    parameters: {
      path: {
        licenceId: number
      }
    }
    responses: {
      /** Address updated */
      200: unknown
      /** Bad request, request body must be valid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** The licence for this ID was not found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AppointmentAddressRequest']
      }
    }
  }
  /** Update the set of additional conditions on the licence. This does not include accompanying data per condition. Existing conditions which appear on the licence but which are not supplied to this endpoint will be deleted. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
  updateAdditionalConditions: {
    parameters: {
      path: {
        licenceId: number
      }
    }
    responses: {
      /** Set of additional conditions updated */
      200: unknown
      /** Bad request, request body must be valid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** The licence for this ID was not found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AdditionalConditionsRequest']
      }
    }
  }
  /** Update the user entered data to accompany an additional condition template. Existing data for a condition which does not appear in this request will be deleted. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
  updateAdditionalConditionData: {
    parameters: {
      path: {
        licenceId: number
        additionalConditionId: number
      }
    }
    responses: {
      /** Additional condition updated */
      200: unknown
      /** Bad request, request body must be valid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** The licence for this ID was not found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAdditionalConditionDataRequest']
      }
    }
  }
  /** Removes a previously uploaded exclusion zone file. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
  removeExclusionZoneFile: {
    parameters: {
      path: {
        licenceId: number
        conditionId: number
      }
    }
    responses: {
      /** The exclusion zone file was removed */
      200: unknown
      /** Bad request, request body must be valid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Records an auditable event related to an action taken by a user or an automated in-service process. Requires ROLE_CVL_ADMIN. */
  recordAuditEvent: {
    responses: {
      /** The audit event was recorded */
      200: unknown
      /** Bad request, request body must be valid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AuditEvent']
      }
    }
  }
  /** Creates a licence with the default status IN_PROGRESS and populates with the details provided. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
  createLicence: {
    responses: {
      /** Licence created */
      200: {
        content: {
          'application/json': components['schemas']['LicenceSummary']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateLicenceRequest']
      }
    }
  }
  /** Set licence statuses to ACTIVE. Accepts a list of licence IDs. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
  activateLicences: {
    responses: {
      /** Licences activated */
      200: unknown
      /** Bad request, request body must be valid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': number[]
      }
    }
  }
  /** Uploads a PDF file containing an exclusion zone map and description. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
  uploadExclusionZoneFile: {
    parameters: {
      path: {
        licenceId: number
        conditionId: number
      }
    }
    responses: {
      /** The exclusion zone file was uploaded */
      200: unknown
      /** Bad request, request body must be valid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'multipart/form-data': {
          file: string
        }
      }
    }
  }
  /** Retrieves a list of auditable events matching the criteria provided. Requires ROLE_CVL_ADMIN. */
  requestAuditEvents: {
    responses: {
      /** The a list of matching auditable events is returned. */
      200: {
        content: {
          'application/json': components['schemas']['AuditEvent'][]
        }
      }
      /** Bad request, request body must be valid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AuditRequest']
      }
    }
  }
  /** Get the licences matching the supplied lists of status, prison, staffId and nomsId. Requires ROLE_CVL_ADMIN. */
  getLicencesMatchingCriteria: {
    parameters: {
      query: {
        prison?: string[]
        status?: ('IN_PROGRESS' | 'SUBMITTED' | 'APPROVED' | 'ACTIVE' | 'REJECTED' | 'INACTIVE' | 'RECALLED')[]
        staffId?: number[]
        nomsId?: string[]
        sortBy?: string
        sortOrder?: string
      }
    }
    responses: {
      /** Returned matching licence summary details - empty if no matches. */
      200: {
        content: {
          'application/json': components['schemas']['LicenceSummary'][]
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Returns a single licence detail by its unique identifier. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
  getLicenceById: {
    parameters: {
      path: {
        licenceId: number
      }
    }
    responses: {
      /** Licence found */
      200: {
        content: {
          'application/json': components['schemas']['Licence']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** The licence for this ID was not found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  /** Get the exclusion zone map image. Requires ROLE_SYSTEM_USER or ROLE_CVL_ADMIN. */
  getExclusionZoneImage: {
    parameters: {
      path: {
        licenceId: number
        conditionId: number
      }
    }
    responses: {
      /** Image returned */
      200: {
        content: {
          'image/jpeg': unknown
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** No image was found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
