apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: activate-licences
spec:
  schedule: "0 3 * * *" # 3am every day
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 43200
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: create-and-vary-a-licence
            image: {{ with index .Values "generic-service" }}{{ .image.repository }}:{{ .image.tag }}{{ end }}
            args:
            - node
            - dist/jobs/updateLicences
{{- include "deployment.envs" (index .Values "generic-service") | nindent 12 }}
          restartPolicy: Never
          activeDeadlineSeconds: 3600
