apiVersion: batch/v1
kind: CronJob
metadata:
  name: remove-ap-conditions
spec:
  schedule: {{ .Values.cronjobs.remove_expired_conditions }}
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 43200
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: create-and-vary-a-licence
            image: {{ with index .Values "generic-service" }}{{ .image.repository }}:{{ .image.tag }}{{ end }}
            args:
            - node
            - dist/jobs/removeExpiredConditions
{{- include "deployment.envs" (index .Values "generic-service") | nindent 12 }}
          restartPolicy: Never
          activeDeadlineSeconds: 3600
