import { templateRenderer } from '../../utils/__testutils/templateTestUtils'

const render = templateRenderer(
  '{% from "pages/approverImmediateReleaseConditions.njk" import approverImmediateReleaseConditions %}{{ approverImmediateReleaseConditions(options)}}',
)

describe('approverImmediateReleaseConditions', () => {
  it('should display standard conditions text', () => {
    const $ = render({
      options: {
        kind: 'HARD_STOP',
        submittedByFullName: 'Bob Smith',
        prisonDescription: 'prison',
        typeCode: 'AP',
      },
    })
    expect($('.licence-conditions').text().toString()).toContain('standard conditions')
    expect($('p').text().toString()).toContain('No other additional or bespoke licence conditions can be added.')
  })

  it('should display post sentence supervision text', () => {
    const $ = render({
      options: {
        kind: 'HARD_STOP',
        submittedByFullName: 'Bob Smith',
        prisonDescription: 'prison',
        typeCode: 'PSS',
      },
    })
    expect($('.licence-conditions').text().toString()).toContain(
      'This licence contains standard post sentence supervision requirements only by default.',
    )
    expect($('p').text().toString()).not.toContain('No other additional or bespoke licence conditions can be added.')
  })

  it('should display hard stop warning text', () => {
    const $ = render({
      options: {
        kind: 'HARD_STOP',
        submittedByFullName: 'Bob Smith',
        prisonDescription: 'prison',
        typeCode: 'AP',
      },
    })
    expect($('.govuk-warning-text__text').text().toString()).toContain(
      'This licence was generated by Bob Smith at OMU prison as the probation practitioner did not submit one in time for final release checks.',
    )
  })

  it('should display time served warning text', () => {
    const $ = render({
      options: {
        kind: 'TIME_SERVED',
        submittedByFullName: 'Alice Johnson',
        prisonDescription: 'Alcatraz',
        typeCode: 'PSS',
      },
    })
    expect($('.govuk-warning-text__text').text().toString()).toContain(
      'This licence was generated by Alice Johnson at Alcatraz as this person is being released with time served.',
    )
  })
})
